apiVersion: v1
kind: Service
metadata:
  name: ms-participantes
spec:
  selector:
    app: ms-participantes
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort