apiVersion: v1
kind: Service
metadata:
  name: oracle-eventos
spec:
  type: NodePort
  selector:
    app: oracle-eventos
  ports:
    - name: oracle
      protocol: TCP
      port: 1521
      targetPort: 1521
      nodePort: 30011
