apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-participantes-pv
  namespace: gestion-ep-dev
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/oracle-participantes
