apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-participantes-pvc
  namespace: gestion-ep-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
