apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-participantes-config
  namespace: gestion-ep-dev
data:
  APP_NAME: ms-participantes
  SERVER_PORT: "8082"
  DB_URL: jdbc:oracle:thin:@oracle-participantes:1522/XEPDB1
  DB_DRIVER: oracle.jdbc.OracleDriver
  ACTUATOR_PORT: "8082"