apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: gestion-ep-dev
type: Opaque
data:
  EVENTOS_DB_USERNAME: bXNfZXZlbnRvcw==        # Base64 de "ms_eventos"
  EVENTOS_DB_PASSWORD: ZXZlbnRvczEyMw==        # Base64 de "eventos123"
  PARTICIPANTES_DB_USERNAME: bXNfcGFydGljaXBhbnRlcw==  # Base64 de "ms_participantes"
  PARTICIPANTES_DB_PASSWORD: cGFydGljaXBhbnRlczEyMw==  # Base64 de "participantes123"