apiVersion: v1
kind: Service
metadata:
  name: ms-gateway
  namespace: gestion-ep-dev
spec:
  selector:
    app: ms-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9099
  type: LoadBalancer
