apiVersion: v1
kind: Service
metadata:
  name: oracle-participantes
spec:
  type: NodePort
  selector:
    app: oracle-participantes
  ports:
    - name: oracle
      protocol: TCP
      port: 1522
      targetPort: 1521
      nodePort: 30012
