server:
  port: 9099

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      routes:
        - id: ms-eventos
          uri: http://ms-eventos:8081
          predicates:
            - Path=/eventos/**

        - id: ms-participantes
          uri: http://ms-participantes:8082
          predicates:
            - Path=/participantes/**,/inscripciones/**
