version: "3.9"
services:
  oracle-participantes:
    container_name: oracle-participantes
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      ORACLE_PWD: participantes123
      ORACLE_SID: XE
      ORACLE_PDB: XEPDB1
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1522:1521"
    volumes:
      - oracle_participantes_data:/opt/oracle/oradata
      - ./init_schema.sql:/opt/oracle/scripts/startup/init_schema.sql
    networks:
      - ms-network

volumes:
  oracle_participantes_data:

networks:
  ms-network:
    external: true
