CREATE USER ms_participantes IDENTIFIED BY participantes123;
GRANT CONNECT, RESOURCE TO ms_participantes;

ALTER USER ms_participantes QUOTA UNLIMITED ON USERS;

CREATE TABLE ms_participantes.participante (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres       VARCHAR2(100) NOT NULL,
    apellidos     VARCHAR2(100),
    email         VARCHAR2(150) NOT NULL UNIQUE,
    telefono      VARCHAR2(20),
    registrado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ms_participantes.inscripcion (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_participante   NUMBER NOT NULL,
    id_evento         NUMBER NOT NULL,
    fecha_inscripcion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado            VARCHAR2(20) DEFAULT 'registrado',
    CONSTRAINT fk_participante FOREIGN KEY (id_participante)
      REFERENCES ms_participantes.participante(id)
);
