version: "3.9"

services:
  oracle-eventos:
    container_name: oracle-eventos
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      ORACLE_PWD: eventos123
      ORACLE_SID: XE
      ORACLE_PDB: XEPDB1
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_eventos_data:/opt/oracle/oradata
      - ./eventos/init_schema_eventos.sql:/opt/oracle/scripts/startup/init_schema_eventos.sql
    networks:
      - ms-network

  oracle-participantes:
    container_name: oracle-participantes
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      ORACLE_PWD: participantes123
      ORACLE_SID: XE
      ORACLE_PDB: XEPDB1
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1522:1521"
      - "5501:5500"
    volumes:
      - oracle_participantes_data:/opt/oracle/oradata
      - ./participantes/init_schema_participantes.sql:/opt/oracle/scripts/startup/init_schema_participantes.sql
    networks:
      - ms-network

volumes:
  oracle_eventos_data:
    name: oracle_eventos_data
  oracle_participantes_data:
    name: oracle_participantes_data

networks:
  ms-network:
    external: true
